import types
from typing import Callable

API_NAME: str
QT_VERSION: str
API_NAME: str
PYSIDE2: bool
PYSIDE6: bool
PYQT5: bool
PYQT6: bool

_get_submodule: Callable[[str, types.ModuleType]]

from PyQt5 import (
    QtBluetooth,
    QtCore,
    QtDBus,
    QtDesigner,
    QtGui,
    QtHelp,
    QtLocation,
    QtMacExtras,
    QtMultimedia,
    QtMultimediaWidgets,
    QtNetwork,
    QtNfc,
    QtOpenGL,
    QtPositioning,
    QtPrintSupport,
    QtQml,
    QtQuick,
    QtQuick3D,
    QtQuickWidgets,
    QtRemoteObjects,
    QtSensors,
    QtSerialPort,
    QtSql,
    QtSvg,
    QtTest,
    QtTextToSpeech,
    QtWebChannel,
    QtWebSockets,
    QtWidgets,
    QtXml,
    QtXmlPatterns,
    sip,
)
from PyQt6 import (
    QtCore,
    QtDBus,
    QtDesigner,
    QtGui,
    QtHelp,
    QtNetwork,
    QtOpenGL,
    QtOpenGLWidgets,
    QtPrintSupport,
    QtQml,
    QtQuick,
    QtQuick3D,
    QtQuickWidgets,
    QtSql,
    QtSvg,
    QtSvgWidgets,
    QtTest,
    QtWidgets,
    QtXml,
    sip,
)
from PySide2 import (
    Qt3DAnimation,
    Qt3DCore,
    Qt3DExtras,
    Qt3DInput,
    Qt3DLogic,
    Qt3DRender,
    QtCharts,
    QtConcurrent,
    QtCore,
    QtDataVisualization,
    QtGui,
    QtHelp,
    QtLocation,
    QtMacExtras,
    QtMultimedia,
    QtMultimediaWidgets,
    QtNetwork,
    QtOpenGL,
    QtOpenGLFunctions,
    QtPositioning,
    QtPrintSupport,
    QtQml,
    QtQuick,
    QtQuickControls2,
    QtQuickWidgets,
    QtRemoteObjects,
    QtScript,
    QtScriptTools,
    QtScxml,
    QtSensors,
    QtSerialPort,
    QtSql,
    QtSvg,
    QtTest,
    QtTextToSpeech,
    QtUiTools,
    QtWebChannel,
    QtWebEngine,
    QtWebEngineCore,
    QtWebEngineWidgets,
    QtWebSockets,
    QtWidgets,
    QtXml,
    QtXmlPatterns,
)
from PySide6 import (
    Qt3DAnimation,
    Qt3DCore,
    Qt3DExtras,
    Qt3DInput,
    Qt3DLogic,
    Qt3DRender,
    QtCharts,
    QtConcurrent,
    QtCore,
    QtDataVisualization,
    QtDesigner,
    QtGui,
    QtHelp,
    QtNetwork,
    QtOpenGL,
    QtOpenGLWidgets,
    QtPrintSupport,
    QtQml,
    QtQuick,
    QtQuickControls2,
    QtQuickWidgets,
    QtScxml,
    QtSql,
    QtStateMachine,
    QtSvg,
    QtSvgWidgets,
    QtTest,
    QtUiTools,
    QtWidgets,
    QtXml,
)
